#!/usr/bin/env node
// Bundles the multi-file dev sources (src/index.template.html + src/*.js) back into
// the single, dependency-free index.html at the repo root — the file the README
// tells players to download and double-click, and what GitHub Pages serves directly
// with no build step of its own. No bundler dependency on purpose: this project's
// whole pitch is "zero setup," and that has to hold for players AND contributors.
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_HTML = path.join(ROOT, 'src', 'index.template.html');
const OUT_HTML = path.join(ROOT, 'index.html');

const SCRIPT_SRC_RE = /<script\s+src="([^"]+)"\s*><\/script>/g;

function inlineLocalScripts(html) {
  return html.replace(SCRIPT_SRC_RE, (match, src) => {
    if (/^https?:\/\//.test(src)) return match; // leave remote scripts alone
    const filePath = path.join(ROOT, src);
    if (!fs.existsSync(filePath)) {
      throw new Error(`build.js: referenced script not found: ${src}`);
    }
    const code = fs.readFileSync(filePath, 'utf8');
    if (code.includes('</script>')) {
      throw new Error(`build.js: ${src} contains a literal "</script>" and can't be inlined safely`);
    }
    return `<script>\n${code}\n</script>`;
  });
}

const GENERATED_BANNER = '<!-- AUTO-GENERATED by build.js from src/index.template.html + src/*.js — do not edit directly, edit the sources and run `node build.js` -->\n';

function build() {
  const html = fs.readFileSync(SRC_HTML, 'utf8');
  const bundled = GENERATED_BANNER + inlineLocalScripts(html);
  fs.writeFileSync(OUT_HTML, bundled);
  const kb = (Buffer.byteLength(bundled) / 1024).toFixed(0);
  console.log(`Built index.html (${kb} KB)`);
}

build();
